name: cicd

on:
  workflow_dispatch:

jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: Copy code
        run: echo "cloned"

  build:
    needs: [code]
    runs-on: ubuntu-latest
    steps:
      - name: Build code
        run: echo "build"

  test:
    needs: [build]
    runs:
      - name: Test code
        run: echo "tested"

  deploy:
    needs: [code, build]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy code
        run: echo "deployed"
